# Use an official Node.js runtime as the base image for building the React app
FROM node:14-alpine as build

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code to the container
COPY . .

# Build the React app
RUN npm run build

# Use a lightweight web server to serve the built React app
FROM nginx:alpine

# Copy the built app from the build container to the web server directory
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Expose the default HTTP port
EXPOSE 80

# Start the web server
CMD ["nginx", "-g", "daemon off;"]