version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    environment:
      - MONOG_URL="mongodb+srv://sahil:sahilbhatt@testing.jcn48rr.mongodb.net/?retryWrites=true&w=majority"

  react-app:
    build:
      context: ../frontend/
      dockerfile: dockerfile
    ports:
      - 80:80

volumes:
  mongodb_data: